sudo: false
language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO=1.10
  - DJANGO=1.11

matrix:
  fast_finish: true
  include:
  - python: "3.5"
    env: TOXENV=flake8
  - python: "3.5"
    env: TOXENV=docs

before_install: pip install codecov
install: pip install tox

script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGO == '1.10' ]]; then export TOXENV=py27-django110; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGO == '1.11' ]]; then export TOXENV=py27-django111; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' && $DJANGO == '1.10' ]]; then export TOXENV=py34-django110; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' && $DJANGO == '1.11' ]]; then export TOXENV=py34-django111; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $DJANGO == '1.10' ]]; then export TOXENV=py35-django110; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $DJANGO == '1.11' ]]; then export TOXENV=py35-django111; fi"
  - tox -e $TOXENV

after_success: codecov
